import 'package:icare/models/user.dart';
import 'package:icare/models/app_enums.dart';
import 'package:icare/models/health_program.dart';

/// Sample Data Service
///
/// Generates sample ecosystem data for testing the connected virtual hospital
/// Creates realistic test data for patients, doctors, labs, pharmacies, and programs
class SampleDataService {
  static final SampleDataService _instance = SampleDataService._internal();
  factory SampleDataService() => _instance;
  SampleDataService._internal();

  /// Generate 10 sample patients
  List<User> generateSamplePatients() {
    return [
      User(
        id: 'patient_001',
        email: 'john.doe@email.com',
        name: 'John Doe',
        role: UserRole.patient,
        phoneNumber: '+1234567890',
        dateOfBirth: DateTime(1985, 3, 15),
        gender: 'Male',
        address: '123 Main St, New York, NY 10001',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 180)),
      ),
      User(
        id: 'patient_002',
        email: 'sarah.johnson@email.com',
        name: 'Sarah Johnson',
        role: UserRole.patient,
        phoneNumber: '+1234567891',
        dateOfBirth: DateTime(1990, 7, 22),
        gender: 'Female',
        address: '456 Oak Ave, Los Angeles, CA 90001',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 150)),
      ),
      User(
        id: 'patient_003',
        email: 'michael.chen@email.com',
        name: 'Michael Chen',
        role: UserRole.patient,
        phoneNumber: '+1234567892',
        dateOfBirth: DateTime(1978, 11, 8),
        gender: 'Male',
        address: '789 Pine Rd, Chicago, IL 60601',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 120)),
      ),
      User(
        id: 'patient_004',
        email: 'emily.davis@email.com',
        name: 'Emily Davis',
        role: UserRole.patient,
        phoneNumber: '+1234567893',
        dateOfBirth: DateTime(1995, 2, 14),
        gender: 'Female',
        address: '321 Elm St, Houston, TX 77001',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 90)),
      ),
      User(
        id: 'patient_005',
        email: 'david.wilson@email.com',
        name: 'David Wilson',
        role: UserRole.patient,
        phoneNumber: '+1234567894',
        dateOfBirth: DateTime(1982, 9, 30),
        gender: 'Male',
        address: '654 Maple Dr, Phoenix, AZ 85001',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 75)),
      ),
      User(
        id: 'patient_006',
        email: 'lisa.martinez@email.com',
        name: 'Lisa Martinez',
        role: UserRole.patient,
        phoneNumber: '+1234567895',
        dateOfBirth: DateTime(1988, 5, 18),
        gender: 'Female',
        address: '987 Cedar Ln, Philadelphia, PA 19101',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 60)),
      ),
      User(
        id: 'patient_007',
        email: 'robert.taylor@email.com',
        name: 'Robert Taylor',
        role: UserRole.patient,
        phoneNumber: '+1234567896',
        dateOfBirth: DateTime(1975, 12, 5),
        gender: 'Male',
        address: '147 Birch St, San Antonio, TX 78201',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 45)),
      ),
      User(
        id: 'patient_008',
        email: 'jennifer.anderson@email.com',
        name: 'Jennifer Anderson',
        role: UserRole.patient,
        phoneNumber: '+1234567897',
        dateOfBirth: DateTime(1992, 8, 27),
        gender: 'Female',
        address: '258 Spruce Ave, San Diego, CA 92101',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
      ),
      User(
        id: 'patient_009',
        email: 'william.thomas@email.com',
        name: 'William Thomas',
        role: UserRole.patient,
        phoneNumber: '+1234567898',
        dateOfBirth: DateTime(1980, 4, 11),
        gender: 'Male',
        address: '369 Willow Rd, Dallas, TX 75201',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
      ),
      User(
        id: 'patient_010',
        email: 'amanda.jackson@email.com',
        name: 'Amanda Jackson',
        role: UserRole.patient,
        phoneNumber: '+1234567899',
        dateOfBirth: DateTime(1987, 10, 23),
        gender: 'Female',
        address: '741 Ash Blvd, San Jose, CA 95101',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
    ];
  }

  /// Generate 10 sample doctors
  List<User> generateSampleDoctors() {
    return [
      User(
        id: 'doctor_001',
        email: 'dr.sarah.johnson@hospital.com',
        name: 'Dr. Sarah Johnson',
        role: UserRole.doctor,
        phoneNumber: '+1234560001',
        dateOfBirth: DateTime(1980, 6, 15),
        gender: 'Female',
        specialization: 'Cardiology',
        licenseNumber: 'MD-CAR-12345',
        yearsOfExperience: 15,
        isActive: true,
        isApproved: true,
        createdAt: DateTime.now().subtract(const Duration(days: 365)),
      ),
      User(
        id: 'doctor_002',
        email: 'dr.mike.chen@hospital.com',
        name: 'Dr. Mike Chen',
        role: UserRole.doctor,
        phoneNumber: '+1234560002',
        dateOfBirth: DateTime(1975, 3, 22),
        gender: 'Male',
        specialization: 'General Practice',
        licenseNumber: 'MD-GP-23456',
        yearsOfExperience: 20,
        isActive: true,
        isApproved: true,
        createdAt: DateTime.now().subtract(const Duration(days: 350)),
      ),
      User(
        id: 'doctor_003',
        email: 'dr.emily.davis@hospital.com',
        name: 'Dr. Emily Davis',
        role: UserRole.doctor,
        phoneNumber: '+1234560003',
        dateOfBirth: DateTime(1982, 9, 8),
        gender: 'Female',
        specialization: 'Endocrinology',
        licenseNumber: 'MD-END-34567',
        yearsOfExperience: 12,
        isActive: true,
        isApproved: true,
        createdAt: DateTime.now().subtract(const Duration(days: 330)),
      ),
      User(
        id: 'doctor_004',
        email: 'dr.james.wilson@hospital.com',
        name: 'Dr. James Wilson',
        role: UserRole.doctor,
        phoneNumber: '+1234560004',
        dateOfBirth: DateTime(1978, 11, 30),
        gender: 'Male',
        specialization: 'Neurology',
        licenseNumber: 'MD-NEU-45678',
        yearsOfExperience: 18,
        isActive: true,
        isApproved: true,
        createdAt: DateTime.now().subtract(const Duration(days: 310)),
      ),
      User(
        id: 'doctor_005',
        email: 'dr.maria.garcia@hospital.com',
        name: 'Dr. Maria Garcia',
        role: UserRole.doctor,
        phoneNumber: '+1234560005',
        dateOfBirth: DateTime(1985, 4, 17),
        gender: 'Female',
        specialization: 'Pediatrics',
        licenseNumber: 'MD-PED-56789',
        yearsOfExperience: 10,
        isActive: true,
        isApproved: true,
        createdAt: DateTime.now().subtract(const Duration(days: 290)),
      ),
      User(
        id: 'doctor_006',
        email: 'dr.robert.brown@hospital.com',
        name: 'Dr. Robert Brown',
        role: UserRole.doctor,
        phoneNumber: '+1234560006',
        dateOfBirth: DateTime(1973, 7, 25),
        gender: 'Male',
        specialization: 'Orthopedics',
        licenseNumber: 'MD-ORT-67890',
        yearsOfExperience: 22,
        isActive: true,
        isApproved: true,
        createdAt: DateTime.now().subtract(const Duration(days: 270)),
      ),
      User(
        id: 'doctor_007',
        email: 'dr.linda.martinez@hospital.com',
        name: 'Dr. Linda Martinez',
        role: UserRole.doctor,
        phoneNumber: '+1234560007',
        dateOfBirth: DateTime(1988, 1, 12),
        gender: 'Female',
        specialization: 'Dermatology',
        licenseNumber: 'MD-DER-78901',
        yearsOfExperience: 8,
        isActive: true,
        isApproved: true,
        createdAt: DateTime.now().subtract(const Duration(days: 250)),
      ),
      User(
        id: 'doctor_008',
        email: 'dr.thomas.anderson@hospital.com',
        name: 'Dr. Thomas Anderson',
        role: UserRole.doctor,
        phoneNumber: '+1234560008',
        dateOfBirth: DateTime(1981, 5, 19),
        gender: 'Male',
        specialization: 'Psychiatry',
        licenseNumber: 'MD-PSY-89012',
        yearsOfExperience: 14,
        isActive: true,
        isApproved: true,
        createdAt: DateTime.now().subtract(const Duration(days: 230)),
      ),
      User(
        id: 'doctor_009',
        email: 'dr.patricia.taylor@hospital.com',
        name: 'Dr. Patricia Taylor',
        role: UserRole.doctor,
        phoneNumber: '+1234560009',
        dateOfBirth: DateTime(1979, 8, 6),
        gender: 'Female',
        specialization: 'Obstetrics & Gynecology',
        licenseNumber: 'MD-OBG-90123',
        yearsOfExperience: 16,
        isActive: true,
        isApproved: true,
        createdAt: DateTime.now().subtract(const Duration(days: 210)),
      ),
      User(
        id: 'doctor_010',
        email: 'dr.kevin.lee@hospital.com',
        name: 'Dr. Kevin Lee',
        role: UserRole.doctor,
        phoneNumber: '+1234560010',
        dateOfBirth: DateTime(1984, 12, 28),
        gender: 'Male',
        specialization: 'Pulmonology',
        licenseNumber: 'MD-PUL-01234',
        yearsOfExperience: 11,
        isActive: true,
        isApproved: true,
        createdAt: DateTime.now().subtract(const Duration(days: 190)),
      ),
    ];
  }

  /// Generate 10 sample laboratories
  List<LabInfo> generateSampleLabs() {
    return [
      LabInfo(
        id: 'lab_001',
        name: 'CityLab Diagnostics',
        email: 'contact@citylab.com',
        phoneNumber: '+1234570001',
        address: '100 Medical Plaza, New York, NY 10001',
        licenseNumber: 'LAB-NY-10001',
        specializations: ['Blood Tests', 'Urinalysis', 'Microbiology'],
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 400)),
      ),
      LabInfo(
        id: 'lab_002',
        name: 'MedTest Laboratory',
        email: 'info@medtest.com',
        phoneNumber: '+1234570002',
        address: '250 Health Center Dr, Los Angeles, CA 90001',
        licenseNumber: 'LAB-CA-20002',
        specializations: ['Pathology', 'Histology', 'Cytology'],
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 380)),
      ),
      LabInfo(
        id: 'lab_003',
        name: 'QuickDiagnostics Inc',
        email: 'service@quickdiag.com',
        phoneNumber: '+1234570003',
        address: '500 Science Blvd, Chicago, IL 60601',
        licenseNumber: 'LAB-IL-30003',
        specializations: ['Radiology', 'Imaging', 'X-Ray'],
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 360)),
      ),
      LabInfo(
        id: 'lab_004',
        name: 'Precision Lab Services',
        email: 'contact@precisionlab.com',
        phoneNumber: '+1234570004',
        address: '750 Research Park, Houston, TX 77001',
        licenseNumber: 'LAB-TX-40004',
        specializations: ['Molecular Biology', 'Genetics', 'DNA Testing'],
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 340)),
      ),
      LabInfo(
        id: 'lab_005',
        name: 'HealthCheck Laboratories',
        email: 'info@healthcheck.com',
        phoneNumber: '+1234570005',
        address: '300 Wellness Way, Phoenix, AZ 85001',
        licenseNumber: 'LAB-AZ-50005',
        specializations: ['Blood Tests', 'Hormone Testing', 'Allergy Testing'],
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 320)),
      ),
      LabInfo(
        id: 'lab_006',
        name: 'Advanced Diagnostics Center',
        email: 'contact@advdiag.com',
        phoneNumber: '+1234570006',
        address: '450 Medical Mile, Philadelphia, PA 19101',
        licenseNumber: 'LAB-PA-60006',
        specializations: ['Cardiology Tests', 'ECG', 'Stress Tests'],
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 300)),
      ),
      LabInfo(
        id: 'lab_007',
        name: 'BioTest Solutions',
        email: 'service@biotest.com',
        phoneNumber: '+1234570007',
        address: '600 Innovation Dr, San Antonio, TX 78201',
        licenseNumber: 'LAB-TX-70007',
        specializations: ['Immunology', 'Serology', 'Virology'],
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 280)),
      ),
      LabInfo(
        id: 'lab_008',
        name: 'Rapid Results Lab',
        email: 'info@rapidresults.com',
        phoneNumber: '+1234570008',
        address: '800 Tech Center, San Diego, CA 92101',
        licenseNumber: 'LAB-CA-80008',
        specializations: ['Blood Tests', 'Urinalysis', 'Drug Screening'],
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 260)),
      ),
      LabInfo(
        id: 'lab_009',
        name: 'Elite Medical Testing',
        email: 'contact@elitemedtest.com',
        phoneNumber: '+1234570009',
        address: '900 Healthcare Plaza, Dallas, TX 75201',
        licenseNumber: 'LAB-TX-90009',
        specializations: ['Pathology', 'Biopsy Analysis', 'Cancer Screening'],
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 240)),
      ),
      LabInfo(
        id: 'lab_010',
        name: 'Comprehensive Lab Network',
        email: 'service@complab.com',
        phoneNumber: '+1234570010',
        address: '1000 Medical Complex, San Jose, CA 95101',
        licenseNumber: 'LAB-CA-10010',
        specializations: ['Full Panel Testing', 'Metabolic Tests', 'Lipid Profile'],
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 220)),
      ),
    ];
  }

  /// Generate 10 sample pharmacies
  List<PharmacyInfo> generateSamplePharmacies() {
    return [
      PharmacyInfo(
        id: 'pharmacy_001',
        name: 'HealthPlus Pharmacy',
        email: 'orders@healthplus.com',
        phoneNumber: '+1234580001',
        address: '150 Main St, New York, NY 10001',
        licenseNumber: 'PHR-NY-10001',
        operatingHours: '8:00 AM - 10:00 PM',
        deliveryAvailable: true,
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 420)),
      ),
      PharmacyInfo(
        id: 'pharmacy_002',
        name: 'MediCare Drugstore',
        email: 'service@medicare-drugs.com',
        phoneNumber: '+1234580002',
        address: '300 Oak Ave, Los Angeles, CA 90001',
        licenseNumber: 'PHR-CA-20002',
        operatingHours: '24/7',
        deliveryAvailable: true,
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 400)),
      ),
      PharmacyInfo(
        id: 'pharmacy_003',
        name: 'QuickMeds Pharmacy',
        email: 'orders@quickmeds.com',
        phoneNumber: '+1234580003',
        address: '550 Pine Rd, Chicago, IL 60601',
        licenseNumber: 'PHR-IL-30003',
        operatingHours: '7:00 AM - 11:00 PM',
        deliveryAvailable: true,
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 380)),
      ),
      PharmacyInfo(
        id: 'pharmacy_004',
        name: 'Wellness Pharmacy',
        email: 'contact@wellnesspharm.com',
        phoneNumber: '+1234580004',
        address: '400 Elm St, Houston, TX 77001',
        licenseNumber: 'PHR-TX-40004',
        operatingHours: '8:00 AM - 9:00 PM',
        deliveryAvailable: true,
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 360)),
      ),
      PharmacyInfo(
        id: 'pharmacy_005',
        name: 'CityRx Pharmacy',
        email: 'service@cityrx.com',
        phoneNumber: '+1234580005',
        address: '700 Maple Dr, Phoenix, AZ 85001',
        licenseNumber: 'PHR-AZ-50005',
        operatingHours: '9:00 AM - 8:00 PM',
        deliveryAvailable: false,
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 340)),
      ),
      PharmacyInfo(
        id: 'pharmacy_006',
        name: 'Express Pharmacy',
        email: 'orders@expresspharm.com',
        phoneNumber: '+1234580006',
        address: '200 Cedar Ln, Philadelphia, PA 19101',
        licenseNumber: 'PHR-PA-60006',
        operatingHours: '24/7',
        deliveryAvailable: true,
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 320)),
      ),
      PharmacyInfo(
        id: 'pharmacy_007',
        name: 'Community Pharmacy',
        email: 'info@communitypharm.com',
        phoneNumber: '+1234580007',
        address: '350 Birch St, San Antonio, TX 78201',
        licenseNumber: 'PHR-TX-70007',
        operatingHours: '8:00 AM - 10:00 PM',
        deliveryAvailable: true,
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 300)),
      ),
      PharmacyInfo(
        id: 'pharmacy_008',
        name: 'PrimeMeds Pharmacy',
        email: 'service@primemeds.com',
        phoneNumber: '+1234580008',
        address: '500 Spruce Ave, San Diego, CA 92101',
        licenseNumber: 'PHR-CA-80008',
        operatingHours: '7:00 AM - 11:00 PM',
        deliveryAvailable: true,
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 280)),
      ),
      PharmacyInfo(
        id: 'pharmacy_009',
        name: 'TrueCare Pharmacy',
        email: 'orders@truecare.com',
        phoneNumber: '+1234580009',
        address: '650 Willow Rd, Dallas, TX 75201',
        licenseNumber: 'PHR-TX-90009',
        operatingHours: '8:00 AM - 9:00 PM',
        deliveryAvailable: true,
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 260)),
      ),
      PharmacyInfo(
        id: 'pharmacy_010',
        name: 'LifeLine Pharmacy',
        email: 'contact@lifelinepharm.com',
        phoneNumber: '+1234580010',
        address: '800 Ash Blvd, San Jose, CA 95101',
        licenseNumber: 'PHR-CA-10010',
        operatingHours: '24/7',
        deliveryAvailable: true,
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 240)),
      ),
    ];
  }
}

/// Lab information model
class LabInfo {
  final String id;
  final String name;
  final String email;
  final String phoneNumber;
  final String address;
  final String licenseNumber;
  final List<String> specializations;
  final bool isActive;
  final DateTime createdAt;

  LabInfo({
    required this.id,
    required this.name,
    required this.email,
    required this.phoneNumber,
    required this.address,
    required this.licenseNumber,
    required this.specializations,
    required this.isActive,
    required this.createdAt,
  });
}

/// Pharmacy information model
class PharmacyInfo {
  final String id;
  final String name;
  final String email;
  final String phoneNumber;
  final String address;
  final String licenseNumber;
  final String operatingHours;
  final bool deliveryAvailable;
  final bool isActive;
  final DateTime createdAt;

  PharmacyInfo({
    required this.id,
    required this.name,
    required this.email,
    required this.phoneNumber,
    required this.address,
    required this.licenseNumber,
    required this.operatingHours,
    required this.deliveryAvailable,
    required this.isActive,
    required this.createdAt,
  });
}

extension SampleDataServiceHealthPrograms on SampleDataService {
  /// Generate 10 sample health programs
  List<HealthProgram> generateSampleHealthPrograms() {
    return [
      HealthProgram(
        id: 'program_001',
        name: 'Diabetes Management Program',
        description: 'Comprehensive program for managing Type 2 Diabetes through lifestyle modifications, medication adherence, and regular monitoring.',
        category: HealthProgramCategory.chronicDisease,
        targetCondition: 'Type 2 Diabetes',
        durationWeeks: 12,
        modules: [
          ProgramModule(
            id: 'module_001_1',
            title: 'Understanding Diabetes',
            content: 'Learn about what diabetes is, how it affects your body, and why management is crucial.',
            orderIndex: 1,
            estimatedMinutes: 30,
            resources: ['Video: What is Diabetes?', 'PDF: Diabetes Basics'],
          ),
          ProgramModule(
            id: 'module_001_2',
            title: 'Blood Sugar Monitoring',
            content: 'How to check your blood sugar levels and understand the results.',
            orderIndex: 2,
            estimatedMinutes: 25,
            resources: ['Video: How to Use a Glucometer', 'Chart: Target Blood Sugar Levels'],
          ),
          ProgramModule(
            id: 'module_001_3',
            title: 'Nutrition for Diabetes',
            content: 'Dietary guidelines and meal planning for blood sugar control.',
            orderIndex: 3,
            estimatedMinutes: 40,
            resources: ['PDF: Diabetic Meal Plan', 'Video: Carb Counting'],
          ),
        ],
        instructorId: 'instructor_001',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 200)),
      ),
      HealthProgram(
        id: 'program_002',
        name: 'Hypertension Control Program',
        description: 'Learn to manage high blood pressure through diet, exercise, stress management, and medication.',
        category: HealthProgramCategory.chronicDisease,
        targetCondition: 'Hypertension',
        durationWeeks: 8,
        modules: [
          ProgramModule(
            id: 'module_002_1',
            title: 'Understanding Blood Pressure',
            content: 'What blood pressure means and why it matters for your health.',
            orderIndex: 1,
            estimatedMinutes: 25,
            resources: ['Video: Blood Pressure Explained', 'Infographic: BP Numbers'],
          ),
          ProgramModule(
            id: 'module_002_2',
            title: 'DASH Diet Basics',
            content: 'Dietary approaches to stop hypertension.',
            orderIndex: 2,
            estimatedMinutes: 35,
            resources: ['PDF: DASH Diet Guide', 'Recipe Book: Heart-Healthy Meals'],
          ),
        ],
        instructorId: 'instructor_002',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 180)),
      ),
      HealthProgram(
        id: 'program_003',
        name: 'Heart Health & Prevention',
        description: 'Preventive care program focused on cardiovascular health and reducing heart disease risk.',
        category: HealthProgramCategory.preventiveCare,
        targetCondition: 'Cardiovascular Disease Prevention',
        durationWeeks: 10,
        modules: [
          ProgramModule(
            id: 'module_003_1',
            title: 'Heart Disease Risk Factors',
            content: 'Identify and understand your personal risk factors.',
            orderIndex: 1,
            estimatedMinutes: 30,
            resources: ['Assessment: Heart Risk Calculator', 'Video: Know Your Numbers'],
          ),
        ],
        instructorId: 'instructor_001',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 160)),
      ),
      HealthProgram(
        id: 'program_004',
        name: 'Post-Surgery Recovery',
        description: 'Guided recovery program for patients after surgical procedures.',
        category: HealthProgramCategory.postSurgery,
        targetCondition: 'Post-Operative Care',
        durationWeeks: 6,
        modules: [
          ProgramModule(
            id: 'module_004_1',
            title: 'Wound Care Basics',
            content: 'How to care for your surgical incision and recognize signs of infection.',
            orderIndex: 1,
            estimatedMinutes: 20,
            resources: ['Video: Wound Care', 'Checklist: Warning Signs'],
          ),
        ],
        instructorId: 'instructor_003',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 140)),
      ),
      HealthProgram(
        id: 'program_005',
        name: 'Stress & Anxiety Management',
        description: 'Mental health program teaching coping strategies for stress and anxiety.',
        category: HealthProgramCategory.mentalHealth,
        targetCondition: 'Anxiety Disorders',
        durationWeeks: 8,
        modules: [
          ProgramModule(
            id: 'module_005_1',
            title: 'Understanding Anxiety',
            content: 'Learn about anxiety, its causes, and how it affects your body.',
            orderIndex: 1,
            estimatedMinutes: 30,
            resources: ['Video: What is Anxiety?', 'PDF: Anxiety Symptoms'],
          ),
          ProgramModule(
            id: 'module_005_2',
            title: 'Breathing Techniques',
            content: 'Practice breathing exercises to manage anxiety symptoms.',
            orderIndex: 2,
            estimatedMinutes: 20,
            resources: ['Audio: Guided Breathing', 'Video: Box Breathing'],
          ),
        ],
        instructorId: 'instructor_004',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 120)),
      ),
      HealthProgram(
        id: 'program_006',
        name: 'Healthy Weight Management',
        description: 'Evidence-based program for sustainable weight loss and healthy lifestyle habits.',
        category: HealthProgramCategory.nutrition,
        targetCondition: 'Obesity',
        durationWeeks: 16,
        modules: [
          ProgramModule(
            id: 'module_006_1',
            title: 'Setting Realistic Goals',
            content: 'How to set achievable weight loss goals and track progress.',
            orderIndex: 1,
            estimatedMinutes: 25,
            resources: ['Worksheet: Goal Setting', 'Calculator: BMI & Target Weight'],
          ),
        ],
        instructorId: 'instructor_002',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 100)),
      ),
      HealthProgram(
        id: 'program_007',
        name: 'Prenatal Care & Wellness',
        description: 'Comprehensive program for expectant mothers covering pregnancy health and preparation.',
        category: HealthProgramCategory.prenatal,
        targetCondition: 'Pregnancy',
        durationWeeks: 20,
        modules: [
          ProgramModule(
            id: 'module_007_1',
            title: 'First Trimester Essentials',
            content: 'What to expect and how to stay healthy in early pregnancy.',
            orderIndex: 1,
            estimatedMinutes: 35,
            resources: ['Video: First Trimester Guide', 'PDF: Prenatal Vitamins'],
          ),
        ],
        instructorId: 'instructor_005',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 80)),
      ),
      HealthProgram(
        id: 'program_008',
        name: 'Asthma Action Plan',
        description: 'Learn to manage asthma symptoms, use inhalers correctly, and prevent attacks.',
        category: HealthProgramCategory.chronicDisease,
        targetCondition: 'Asthma',
        durationWeeks: 6,
        modules: [
          ProgramModule(
            id: 'module_008_1',
            title: 'Understanding Asthma',
            content: 'What happens during an asthma attack and common triggers.',
            orderIndex: 1,
            estimatedMinutes: 25,
            resources: ['Video: Asthma Explained', 'Infographic: Asthma Triggers'],
          ),
        ],
        instructorId: 'instructor_003',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 60)),
      ),
      HealthProgram(
        id: 'program_009',
        name: 'Arthritis Pain Management',
        description: 'Strategies for managing arthritis pain and maintaining mobility.',
        category: HealthProgramCategory.chronicDisease,
        targetCondition: 'Arthritis',
        durationWeeks: 8,
        modules: [
          ProgramModule(
            id: 'module_009_1',
            title: 'Types of Arthritis',
            content: 'Understanding different types of arthritis and their symptoms.',
            orderIndex: 1,
            estimatedMinutes: 30,
            resources: ['Video: Arthritis Types', 'PDF: Joint Care Guide'],
          ),
        ],
        instructorId: 'instructor_001',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 40)),
      ),
      HealthProgram(
        id: 'program_010',
        name: 'Sleep Hygiene & Insomnia',
        description: 'Improve sleep quality through evidence-based sleep hygiene practices.',
        category: HealthProgramCategory.general,
        targetCondition: 'Insomnia',
        durationWeeks: 4,
        modules: [
          ProgramModule(
            id: 'module_010_1',
            title: 'Sleep Science Basics',
            content: 'Understanding sleep cycles and why sleep matters.',
            orderIndex: 1,
            estimatedMinutes: 25,
            resources: ['Video: How Sleep Works', 'PDF: Sleep Stages'],
          ),
        ],
        instructorId: 'instructor_004',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
      ),
    ];
  }

  /// Generate 10 sample instructors
  List<User> generateSampleInstructors() {
    return [
      User(
        id: 'instructor_001',
        email: 'instructor.james@icare.com',
        name: 'James Wilson',
        role: UserRole.instructor,
        phoneNumber: '+1234590001',
        dateOfBirth: DateTime(1975, 5, 10),
        gender: 'Male',
        specialization: 'Chronic Disease Management',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 250)),
      ),
      User(
        id: 'instructor_002',
        email: 'instructor.maria@icare.com',
        name: 'Maria Rodriguez',
        role: UserRole.instructor,
        phoneNumber: '+1234590002',
        dateOfBirth: DateTime(1982, 8, 22),
        gender: 'Female',
        specialization: 'Nutrition & Wellness',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 230)),
      ),
      User(
        id: 'instructor_003',
        email: 'instructor.david@icare.com',
        name: 'David Kim',
        role: UserRole.instructor,
        phoneNumber: '+1234590003',
        dateOfBirth: DateTime(1978, 11, 15),
        gender: 'Male',
        specialization: 'Post-Operative Care',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 210)),
      ),
      User(
        id: 'instructor_004',
        email: 'instructor.sarah@icare.com',
        name: 'Sarah Thompson',
        role: UserRole.instructor,
        phoneNumber: '+1234590004',
        dateOfBirth: DateTime(1985, 3, 8),
        gender: 'Female',
        specialization: 'Mental Health & Wellness',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 190)),
      ),
      User(
        id: 'instructor_005',
        email: 'instructor.lisa@icare.com',
        name: 'Lisa Chen',
        role: UserRole.instructor,
        phoneNumber: '+1234590005',
        dateOfBirth: DateTime(1980, 7, 19),
        gender: 'Female',
        specialization: 'Prenatal & Maternal Health',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 170)),
      ),
      User(
        id: 'instructor_006',
        email: 'instructor.michael@icare.com',
        name: 'Michael Brown',
        role: UserRole.instructor,
        phoneNumber: '+1234590006',
        dateOfBirth: DateTime(1973, 12, 3),
        gender: 'Male',
        specialization: 'Cardiology Education',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 150)),
      ),
      User(
        id: 'instructor_007',
        email: 'instructor.jennifer@icare.com',
        name: 'Jennifer Lee',
        role: UserRole.instructor,
        phoneNumber: '+1234590007',
        dateOfBirth: DateTime(1987, 4, 27),
        gender: 'Female',
        specialization: 'Diabetes Education',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 130)),
      ),
      User(
        id: 'instructor_008',
        email: 'instructor.robert@icare.com',
        name: 'Robert Martinez',
        role: UserRole.instructor,
        phoneNumber: '+1234590008',
        dateOfBirth: DateTime(1979, 9, 14),
        gender: 'Male',
        specialization: 'Respiratory Health',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 110)),
      ),
      User(
        id: 'instructor_009',
        email: 'instructor.amanda@icare.com',
        name: 'Amanda White',
        role: UserRole.instructor,
        phoneNumber: '+1234590009',
        dateOfBirth: DateTime(1984, 6, 21),
        gender: 'Female',
        specialization: 'Pain Management',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 90)),
      ),
      User(
        id: 'instructor_010',
        email: 'instructor.kevin@icare.com',
        name: 'Kevin Taylor',
        role: UserRole.instructor,
        phoneNumber: '+1234590010',
        dateOfBirth: DateTime(1981, 1, 30),
        gender: 'Male',
        specialization: 'Sleep Medicine',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 70)),
      ),
    ];
  }

  /// Generate 10 sample students
  List<User> generateSampleStudents() {
    return [
      User(
        id: 'student_001',
        email: 'student.alex@medical.edu',
        name: 'Alex Johnson',
        role: UserRole.student,
        phoneNumber: '+1234591001',
        dateOfBirth: DateTime(1998, 3, 12),
        gender: 'Male',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 180)),
      ),
      User(
        id: 'student_002',
        email: 'student.emma@medical.edu',
        name: 'Emma Davis',
        role: UserRole.student,
        phoneNumber: '+1234591002',
        dateOfBirth: DateTime(1999, 7, 25),
        gender: 'Female',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 170)),
      ),
      User(
        id: 'student_003',
        email: 'student.ryan@medical.edu',
        name: 'Ryan Miller',
        role: UserRole.student,
        phoneNumber: '+1234591003',
        dateOfBirth: DateTime(1997, 11, 8),
        gender: 'Male',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 160)),
      ),
      User(
        id: 'student_004',
        email: 'student.sophia@medical.edu',
        name: 'Sophia Garcia',
        role: UserRole.student,
        phoneNumber: '+1234591004',
        dateOfBirth: DateTime(2000, 2, 14),
        gender: 'Female',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 150)),
      ),
      User(
        id: 'student_005',
        email: 'student.ethan@medical.edu',
        name: 'Ethan Wilson',
        role: UserRole.student,
        phoneNumber: '+1234591005',
        dateOfBirth: DateTime(1998, 9, 30),
        gender: 'Male',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 140)),
      ),
      User(
        id: 'student_006',
        email: 'student.olivia@medical.edu',
        name: 'Olivia Martinez',
        role: UserRole.student,
        phoneNumber: '+1234591006',
        dateOfBirth: DateTime(1999, 5, 18),
        gender: 'Female',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 130)),
      ),
      User(
        id: 'student_007',
        email: 'student.noah@medical.edu',
        name: 'Noah Anderson',
        role: UserRole.student,
        phoneNumber: '+1234591007',
        dateOfBirth: DateTime(1997, 12, 5),
        gender: 'Male',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 120)),
      ),
      User(
        id: 'student_008',
        email: 'student.ava@medical.edu',
        name: 'Ava Thomas',
        role: UserRole.student,
        phoneNumber: '+1234591008',
        dateOfBirth: DateTime(2000, 8, 27),
        gender: 'Female',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 110)),
      ),
      User(
        id: 'student_009',
        email: 'student.liam@medical.edu',
        name: 'Liam Jackson',
        role: UserRole.student,
        phoneNumber: '+1234591009',
        dateOfBirth: DateTime(1998, 4, 11),
        gender: 'Male',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 100)),
      ),
      User(
        id: 'student_010',
        email: 'student.mia@medical.edu',
        name: 'Mia White',
        role: UserRole.student,
        phoneNumber: '+1234591010',
        dateOfBirth: DateTime(1999, 10, 23),
        gender: 'Female',
        isActive: true,
        createdAt: DateTime.now().subtract(const Duration(days: 90)),
      ),
    ];
  }
}
